# Generated by Django 3.1.4 on 2020-12-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='image',
            field=models.TextField(default='placeholder.jpg'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.TextField(default='name'),
        ),
    ]
